
[[constraint]]
  branch = "master"
  name = "github.com/bgentry/go-netrc"

[[constraint]]
  name = "github.com/kevinburke/go-git"
  version = "0.6.0"

[[constraint]]
  name = "github.com/kevinburke/go-types"
  version = "0.23.0"

[[constraint]]
  name = "github.com/kevinburke/rest"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/knq/ini"

[prune]
  go-tests = true
  unused-packages = true
